# -*- coding: utf-8 -*-
"""final_test_file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gfh-iaLU3F5Oi9qr-kQb7bN6Q9ie-Mmr
"""

import random #for random shuffle
import os #for pause below
def pause():
    programPause = input("Press the <ENTER> key to begin the experiment")
    

subject_init=input('Enter your first and last intials here: ')
  
subject_gender=input('Enter M for male, F for female: ')
  
subject_age=input('Enter your age: ')
  
print('')

print('Greetings', subject_init , ',this experiment is an example')
print("of a a basic trials structure that would be integrated with PsychoPy.")
print('')
print('In this task you will asked to press a specific key when the word HOT or')
print('COLD appears on the screen.')
print('Press the x key followed by ENTER when cold appears')
print('Press the z key followed by ENTER when hot appears,')
pause()
print('')
  
trials=['hot', 'cold','hot','hot','hot','hot','hot','hot','hot','hot','hot','cold','cold','cold','cold','cold','cold','cold','cold','cold']
temp_type=[]
response=[]
correct=[]
random.shuffle(trials)
  
for temperature in trials: 
   if temperature == 'hot':
    temp_type.append(1) #codes the number 1 as hot, 2 as cold
   else:
    temp_type.append(2)
#print(temp_type) checking to see if it looked right
  
for i in trials:
  print(i)
  user_response=input()
  if user_response=='z': #if the user pressed z, its coded as 1
        response.append(1)
  elif user_response=='x': #if the user pressed x, 
        response.append(2)
  else:
    response.append(0)
#print(response) this was a step to check the comparsion lists were working
  
for x, y in zip(temp_type, response):
  if x==y:
    correct.append(1)
  else:
    correct.append(0)
#print(correct) another check to see if lists looked right
 
num_correct=correct.count(1)
if num_correct==20:
  print('Excellent, you got a perfect score!')
elif num_correct >= 12:
  print('Nice Work! You scored', num_correct, 'out of 20.')
elif num_correct < 12: 
  print('Good try, you scored', num_correct, 'out of 20. Try again?')
else: 
  print('We did not get a score from you, please try again')

#when the experiment is in script form, the following asserts can be used to
#test the code
assert len(trials)==20
assert isinstance(subject_init, str)
assert isinstance(subject_gender, str)
assert isinstance(subject_age, str)


#Trials_test()